### ISSUE TITLE
Calendar events

### ISSUE THREAD

**Issue by HotAirBalloonist** [MartinAronsen/membermap#45]
I have the selection made to post calendar events up to a year out on the member map.  I began to add events to the calendar.  Some go on the map and some do not.  I do not know why.

Any Ideas?

**Comment by MartinAronsen** [comment]
Send me a personal message with your board URL, and I'll take a look at it.

**Comment by HotAirBalloonist** [comment]
I am so sorry am completely illiterate when it comes to this stuff.  A personal message?  Is that what happens when I click on the blue box up at the top of the page that says Message?  It does not say personal so I can not assume that is what you ment.  I am not trying to be funny I just do not know how to do as you have asked.

 

The Two sites I manage are www.HotAirBalloonist.com and www.theskiskool.com  

 

Both have member map on them and both were just upgraded to verson 4 since I did not want to start all over again but was told it would be easier.  Its NOT!.   So I am now spending hours trying to work out bugs.  And I am not a developer so working out bugs is a horrible and painful and hugely time consuming process.

 

Let me know what you need.

 

Also do you know someone who can help me with my Media page.  I do not like how the articles are displayed and my Video page does not play video.

 

Jeff.

**Comment by MartinAronsen** [comment]
A personal message is the last thing you did, https://invisioncommunity.com/messenger/198363/. Visible to just you and me.
