### ISSUE TITLE
Caching Issue (Members can only see me)

### ISSUE THREAD

**Issue by levikujala** [MartinAronsen/membermap#47]
Hi, I've now got about 400 members on the map, but it seems to be random whether or not people can see those pins. This happens for me also, but sometimes (not every time) I can go to "browse markers" then come back to the main map and there will be a button to refresh the cache. But sometimes clicking that button still doesn't show everyone on the map.

Can you please advise?
Thanks!
Levi

**Comment by MartinAronsen** [comment]
Are you a Community In the Cloud client? Currently looking into an issue where the disk cache file isn't synced across the IPS server cluster.

**Comment by levikujala** [comment]
Yes, we're a cloud client.

**Comment by MartinAronsen** [comment]
Fixed in v3.4.3

**Comment by levikujala** [comment]
Ok, thanks! how do I update the plugin?

**Comment by MartinAronsen** [comment]
Download the new version [here](https://invisioncommunity.com/files/file/3070-member-map/), and follow the instructions in the ZIP file.

**Comment by levikujala** [comment]
thanks:)
